services:
  #nginx
  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80" # port 80 on local machine map to that port 80 on the container

  app:
    build:
      dockerfile: ./php/Dockerfile
      target: app
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: docker-php
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
volumes:
  mysqldata: