services:
  #nginx
  web:
    image: nginx:latest
    ports:
      - "80:80" # port 80 on local machine map to that port 80 on the container
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

      #php
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - /var/www/html/vendor  # will not be overwritten
      - ./app:/var/www/html
      #mysql
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: docker-php
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      #redis
volumes:
  mysqldata: